version: 1.0
os: windows
files:
  - source: \index.html
    destination: C:\inetpub\wwwroot
  - source: \index.html
    destination: C:\Program Files\
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
